[server]
# Server host name
host = "127.0.0.1"
# Socket address to bind
ip = "[::]"
# Port that should be listened on
port = 8080
# Amount of worker threads
# If set to zero Triox will use one worker per physical CPU core
workers = 0
# change this
secret = "asdlkfajsdlk;faj;sdlfkslkdjfaksjdfakldsjfalksdjfs"
# Disable sign_up service to prevent creation of new accounts through the API
registration = false

[files]
# Disable file system modification like uploading or moving files
read_only = false


[database]
# Database type (currently only MySQL is available)
db = "mysql"
# Username of the database user
user = "triox"
# Password of the database user
password = "triox"
# Database address
host = "localhost"
# Username of the database user
port = "3306"
# Name of the database
name = "triox"


[ssl]
# Certificates can be easily created with certbot (https://certbot.eff.org/) by running
# certbot certonly --standalone
# Enable/disable SSL
enabled = false
# Path to the certificate file
certificate = "ssl/cert.pem"
# Path to the key file
key = "ssl/key.pem"
